name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: smarttraffic-aiwebsite  # Working directory set to your project folder

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: smarttraffic-aiwebsite  # Checkout directly into the subfolder

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: npm install
        working-directory: smarttraffic-aiwebsite  # Explicitly set working directory for each step

      - name: Build Next.js Project
        run: npm run build
        working-directory: smarttraffic-aiwebsite

      - name: Export Static Files
        run: npm run export
        working-directory: smarttraffic-aiwebsite

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: smarttraffic-aiwebsite/out  # Output is inside your subfolder

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
